import React from 'react';
import Link from 'next/link';
import { ShieldCheck, Lock, Eye, Globe, UserCheck, Database, Clock, FileText } from 'lucide-react';

const AdSensePrivacy = () => {
 return (
 <div className="w-full font-sans leading-relaxed">
 <div className="text-center mb-12 md:mb-16">
 <ShieldCheck className="w-16 h-16 mx-auto mb-6" />
 <h1 className="font-bold tracking-tight mb-4">Privacy Policy &amp; Ad Disclosure</h1>
 <p className=" font-medium italic">Last Updated: April 2026</p>
 </div>

 {/* Section 1: What Data We Collect */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <Database className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">Information We Collect</h2>
 </div>
 <p className="mb-6">
 When you use the Washington Child Support Schedule Center (WCSSC), we may collect the following types of information:
 </p>
 <ul className="list-disc pl-6 space-y-3 mb-6">
 <li><strong>Usage Data:</strong> Pages visited, time spent on pages, links clicked, and referral sources. This data is collected via Google Analytics and AdSense tracking.</li>
 <li><strong>Device Information:</strong> Browser type, operating system, screen resolution, and device type (desktop, mobile, tablet).</li>
 <li><strong>IP Address:</strong> Your Internet Protocol address is automatically logged by our hosting provider (Vercel) and by Google AdSense for geographic ad targeting.</li>
 <li><strong>Cookies:</strong> Small text files placed on your device by Google AdSense and analytics services (see Cookie section below).</li>
 <li><strong>Calculator Inputs:</strong> Income figures and family details you enter into our calculator. <strong>This data is NOT stored on our servers</strong> — all calculations happen locally in your browser and are never transmitted.</li>
 </ul>
 </section>

 {/* Section 2: Google AdSense */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <Globe className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">Google AdSense Disclosure</h2>
 </div>
 <p className="mb-6">
 This website uses Google AdSense, a service for including advertisements from Google Inc. (&quot;Google&quot;). Google AdSense uses &quot;cookies&quot;, which are text files placed on your computer, to help the website analyze how users use the site.
 </p>
 <p className="mb-6">
 Google AdSense also uses so-called Web Beacons (invisible graphics). Through these Web Beacons, information such as traffic on these pages can be evaluated.
 </p>
 <div className="bg-gray-50 p-6 rounded-xl border border-gray-100 italic font-medium ">
 &quot;The information generated by cookies and Web Beacons about the use of this website (including your IP address) and the delivery of advertising formats is transmitted to a Google server in the USA and stored there.&quot;
 </div>
 </section>

 {/* Section 3: DART Cookie */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <Lock className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">The DART Cookie</h2>
 </div>
 <p className="mb-6">
 Google, as a third-party vendor, uses cookies to serve ads on your site. Google&apos;s use of the DART cookie enables it to serve ads to your users based on their visit to your sites and other sites on the Internet.
 </p>
 <p className="mb-6 italic">
 Users may opt out of the use of the DART cookie by visiting the Google ad and content network privacy policy.
 </p>
 </section>

 {/* Section 4: Data Sharing & Cookies */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <Eye className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">Data Sharing &amp; Cookies</h2>
 </div>
 <p className="mb-6 font-medium label-metadata ">Mandatory Third-Party Disclosure:</p>
 <ul className="list-disc pl-6 space-y-2 mb-6">
 <li>Third-party vendors, including Google, use cookies to serve ads based on a user&apos;s prior visits to your website or other websites.</li>
 <li>Google&apos;s use of advertising cookies enables it and its partners to serve ads to your users based on their visit to your sites and/or other sites on the Internet.</li>
 <li>Users may opt out of personalized advertising by visiting <Link href="https://www.google.com/settings/ads" className=" underline">Ads Settings</Link>.</li>
 </ul>
 </section>

 {/* Section 5: Data Retention */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <Clock className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">Data Retention</h2>
 </div>
 <p className="mb-6">
 We retain server logs and analytics data for a maximum of <strong>26 months</strong>, consistent with Google Analytics default settings. After this period, data is automatically deleted.
 </p>
 <p className="mb-6">
 Calculator input data (income, children count) is <strong>never stored</strong> — it exists only in your browser session and is discarded when you close or navigate away from the page.
 </p>
 </section>

 {/* Section 6: User Rights — GDPR / CCPA */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <UserCheck className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">Your Privacy Rights</h2>
 </div>

 <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-6">
 <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100">
 <h3 className="text-sm font-semibold uppercase mb-4">GDPR (EU/EEA Users)</h3>
 <ul className="list-disc pl-4 space-y-2 text-sm">
 <li>Right to access your personal data</li>
 <li>Right to rectification of inaccurate data</li>
 <li>Right to erasure (&quot;right to be forgotten&quot;)</li>
 <li>Right to restrict processing</li>
 <li>Right to data portability</li>
 <li>Right to object to processing</li>
 <li>Right to opt out of automated decision-making</li>
 </ul>
 </div>
 <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100">
 <h3 className="text-sm font-semibold uppercase mb-4">CCPA (California Users)</h3>
 <ul className="list-disc pl-4 space-y-2 text-sm">
 <li>Right to know what personal information is collected</li>
 <li>Right to know if personal information is sold or disclosed</li>
 <li>Right to say no to the sale of personal information</li>
 <li>Right to equal service and price (non-discrimination)</li>
 <li>Right to delete personal information</li>
 </ul>
 </div>
 </div>

 <div className="p-6 bg-amber-50 border border-amber-200 rounded-xl">
 <p className="text-sm font-medium text-amber-900">
 <strong>&quot;Do Not Sell My Personal Information&quot;:</strong> WCSSC does not sell your personal information to third parties. Google AdSense may use cookies for personalized advertising; you can opt out via{' '}
 <Link href="https://www.google.com/settings/ads" className=" underline">Google Ads Settings</Link> or{' '}
 <Link href="https://optout.aboutads.info" className=" underline">DAA opt-out</Link>.
 </p>
 </div>
 </section>

 {/* Section 7: Cookie Consent */}
 <section className="mb-12">
 <div className="flex items-center gap-3 mb-6">
 <FileText className="w-6 h-6 text-indigo-600" />
 <h2 className="font-semibold ">Cookie Consent (EU/CA Users)</h2>
 </div>
 <p className="mb-6">
 If you are visiting from the European Union, European Economic Area, or California, please be aware that this site uses cookies for advertising personalization. By continuing to use this site, you consent to the use of cookies as described in this policy.
 </p>
 <p className="mb-6">
 You can manage cookie preferences through your browser settings. Most browsers allow you to refuse cookies or delete existing cookies. Please note that disabling cookies may limit the functionality of this website.
 </p>
 </section>

 {/* Section 8: Contact */}
 <section className="mb-12">
 <h2 className="font-semibold mb-6">Privacy Contact</h2>
 <p className="mb-6">
 For any privacy-related questions, data access requests, or to exercise your rights under GDPR/CCPA, please contact us at:
 </p>
 <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100">
 <p className="font-medium ">Washington Child Support Schedule Center (WCSSC)</p>
 <p className=" font-medium">Email: <a href="mailto:support@wcssc.site" className="underline">support@wcssc.site</a></p>
 <p className="text-sm mt-2">We aim to respond to all privacy requests within 30 days.</p>
 </div>
 </section>

 <div className="p-6 bg-indigo-600 rounded-2xl text-white text-center shadow-sm">
 <h3 className="font-semibold mb-4 tracking-tight italic">Your Trust is Our Priority</h3>
 <p className="opacity-90 leading-relaxed max-w-2xl mx-auto">
 We provide accurate WA child support calculations for educational purposes. We do not sell your personal calculator input data to third parties.
 </p>
 </div>
 </div>
 );
};

export default AdSensePrivacy;
